trainLower = tolower(train$text)



"cash only" = grepl(" cash[- ]only", trainLower),
"close" = grepl(" close[d|r]?", trainLower),
"hit" = grepl(" hit.*miss", trainLower),
"enough" = grepl(" enough", trainLower),
"hate miss" = grepl(" hate", trainLower),
"lack" = grepl(" lack[ing?]", trainLower),
"worst" = grepl(" wors[te]", trainLower),
"disappointed" = grepl(" disappointed", trainLower),
"understaffed" = grepl(" understaffed", trainLower),
"ridiculous" = grepl(" ridiculous", trainLower),
"dissatisfied" = grepl(" dissatisfied", trainLower),
"less well" = grepl(" less.*well", trainLower),
"dirty" = sapply(trainLower, function(x) length(gregexpr(" dirty", x)[[1]])),
"..." = grepl("...*", trainLower),
"terrible" = grepl(" terrible", trainLower),
"average" = grepl(" average", trainLower),
"inferior" = grepl(" inferior", trainLower),
"canned" = grepl(" canned", trainLower),
"grease" = grepl(" grease", trainLower),
"disgusting" = grepl(" disgust[ing|ed]", trainLower),
"only" = sapply(trainLower, function(x) length(gregexpr(" only", x)[[1]])),
"?" = grepl(" ?*", trainLower),
"bad" = sapply(trainLower, function(x) length(gregexpr(" bad", x)[[1]])),
"typical" = grepl(" typical*", trainLower),
"never" = sapply(trainLower, function(x) length(gregexpr(" never", x)[[1]])),
"another try" = grepl(" another try", trainLower),
"long" = grepl(" long", trainLower),
"not the best" = grepl(" not the best", trainLower),
"no clue" = grepl("no clue", trainLower),
"nah" = grepl("nah", trainLower),
"tiny" = sapply(trainLower, function(x) length(gregexpr(" tiny", x)[[1]])),
"naive" = grepl("naive", trainLower),
"slow" = sapply(trainLower, function(x) length(gregexpr(" slow", x)[[1]])),
"noisy" = grepl(" noisy", trainLower),
"however" = sapply(trainLower, function(x) length(gregexpr(" however", x)[[1]])),
"but" = sapply(trainLower, function(x) length(gregexpr(" but", x)[[1]])),
"however" = sapply(trainLower, function(x) length(gregexpr(" though", x)[[1]])),
"though" = grepl(" tho[ugh]?", trainLower),
"drawback" = grepl(" drawback", trainLower),
"cooked" = grepl(" cook[ed]?", trainLower),
"not sure" = grepl(" not sure", trainLower),
"no bathroom" = grepl(" no bathroom", trainLower),
"cramped" = grepl(" cramped", trainLower),
"undercook" = grepl(" undercook[ed]?", trainLower),
"raw" = grepl(" raw", trainLower),
"unfortunately" = grepl(" unfortunately", trainLower),
"not worth" = grepl(" not worth", trainLower),
"samll" = grepl(" small", trainLower),
"not worth" = grepl(" not worth", trainLower),
"seat" = grepl(" seat", trainLower),
"grimy" = grepl(" grimy", trainLower),
"dark" = grepl(" dark", trainLower),
"hole" = grepl(" hole", trainLower),
"dark" = sapply(trainLower, function(x) length(gregexpr(" dark", x)[[1]])),
"stand" = sapply(trainLower, function(x) length(gregexpr(" stand", x)[[1]])),
"plain" = grepl(" plain", trainLower),
"rude" = sapply(trainLower, function(x) length(gregexpr(" rude", x)[[1]])),
"decent" = grepl(" decent", trainLower),
"nothing special" = grepl(" nothing special", trainLower),
"boring" = sapply(trainLower, function(x) length(gregexpr(" boring", x)[[1]])),
"avoid" = grepl(" avoid", trainLower),
"filthy" = grepl(" filthy", trainLower),
"unable" = grepl(" unable", trainLower),
"overbearing" = grepl(" overbearing", trainLower),
"confusing" = grepl(" confus(ing|ed)?", trainLower),
"yell" = grepl(" yell", trainLower),
"slimy" = grepl(" slimy", trainLower),
"no" = sapply(trainLower, function(x) length(gregexpr(" no", x)[[1]])),
"at best" = grepl(" at best", trainLower),
"away" = grepl(" away", trainLower),
"horrible" = grepl(" horrible", trainLower),
"-_-" = grepl(" -_+-", trainLower),
"waste" = grepl(" waste", trainLower),
"horrible" = grepl(" horrible", trainLower),
"waste" = grepl(" waste", trainLower),
"tasteless" = grepl(" tasteless", trainLower),
"cold" = grepl(" cold", trainLower),
"tasteless" = grepl(" tasteless", trainLower),
"cold" = grepl(" cold", trainLower),
"empty" = grepl(" empty", trainLower),
"over" = sapply(trainLower, function(x) length(gregexpr(" over", x)[[1]])),
"soggy" = grepl(" soggy", trainLower),
"dry" = grepl(" dry", trainLower),
"awful" = grepl(" awful", trainLower),
"at all" = grepl(" at all", trainLower),
"oily" = grepl(" oily", trainLower),
"although" = grepl(" although", trainLower),
"ok" = sapply(trainLower, function(x) length(gregexpr(" ok", x)[[1]])),
"inconsistent" = grepl(" inconsistent", trainLower),
"stay away" = grepl(" stay away", trainLower),
"mad" = grepl(" mad", trainLower),
"embarrassing" = grepl(" embarrassing", trainLower),
"mislead" = grepl(" mislead", trainLower),
"incorrectly" = grepl(" incorrectly", trainLower),
"yuck" = grepl(" yuck", trainLower),
"grumpy" = grepl(" grumpy", trainLower),
"early" = grepl(" early", trainLower),
"tried" = grepl(" tried", trainLower),
"complain" = grepl(" complaint?", trainLower),
"dish" = sapply(trainLower, function(x) length(gregexpr(" dish", x)[[1]])),
"fail" = sapply(trainLower, function(x) length(gregexpr(" fail", x)[[1]])),
"joint" = grepl(" joint", trainLower),
"hard" = sapply(trainLower, function(x) length(gregexpr(" hard", x)[[1]])),
"take long" = grepl(" takes? long", trainLower),
"oh well" = grepl(" oh well", trainLower),
"shabby" = grepl(" shabby", trainLower),
"barely" = grepl(" barely", trainLower),
"boo" = grepl(" boo", trainLower),
"crap" = grepl(" crap", trainLower),
"refill" = grepl(" refill[ing]?", trainLower),
"late" = sapply(trainLower, function(x) length(gregexpr(" late", x)[[1]])),
"refuse" = grepl(" refuse?", trainLower),
"unbelievable" = grepl(" unbelievable", trainLower),




#good
"discover" = grepl(" discover", trainLower),
"provide" = grepl(" provide", trainLower),
"positive" = grepl(" positive", trainLower),
"entree" = grepl(" entree", trainLower),
"especially" = grepl(" especially", trainLower),
"unique" = grepl(" unique", trainLower),
"light" = grepl(" light", trainLower),
"vary" = grepl(" var[iet]?y", trainLower),
"crazy" = grepl(" crazy", trainLower),
"roman" = grepl(" roman[tic]?", trainLower),
"decor" = sapply(trainLower, function(x) length(gregexpr(" decor", x)[[1]])),
"potential" = grepl(" potential", trainLower),
"definitely" = grepl(" definite[ly]?", trainLower),
"full" = grepl(" full", trainLower),
"take care" = grepl(" take care", trainLower),
"care about" = grepl(" care about", trainLower),
"incredible" = grepl(" incredible[ly]", trainLower),
"interesting" = grepl(" intersting", trainLower),
"full" = grepl(" full", trainLower),
"fun" = sapply(trainLower, function(x) length(gregexpr(" fun", x)[[1]])),
"decadent" = grepl(" decadent", trainLower),
"tasty" = sapply(trainLower, function(x) length(gregexpr(" tasty", x)[[1]])),
"sweet" = sapply(trainLower, function(x) length(gregexpr(" sweet", x)[[1]])),
"delish" = grepl(" delish", trainLower),
"flavor" = grepl(" flavors?", trainLower),










