---
title: "Natural Language Processing in Yelp Reviews"
author: "Zheng Chang and Victor Kong"
output: pdf_document
linestretch: 1.1
---

\[
\mathrm{\bf Abstract}
\]

***Provide a background discussion of your topic area, aimed at an audience which is statistically knowledgeable but unfamiliar with the topic. The discussion should make it possible for such an audience to understand your research question.***

# Introduction

Natural language processing is the study of human language, its interpretation, and its application to artificial intelligence in interfacing with computers. In any language, diction is generally indicative of the true sentiments of a speaker or writer, and a minor deviation in an account's choice of words can drastically change the perceived intent behind it as a whole. It is typical to strategically use certain words and phrases to most potently emanate a particular tone or to best portray a topic in a specific light.  
&nbsp;&nbsp;&nbsp;&nbsp;The intention of this study was to investigate English language cues that demonstrate either a positive or negative attitude towards the topic of discussion, specifically how positive or negative the sentiment in correspondence to a set of cues. The researched data set consists of restaurant reviews written by users of the web-based social networking site Yelp.com. These reviews were inspected for the presence of certain words and strings, each of which was then examined for correlation with whether the review corresponded to a positive or negative experience. In the context of this study, a positive experience was defined to be one that earned a rating of four or more stars whereas a negative experience was defined to be one that earned a rating of three or less stars. This study involved developing a model to predict whether an experience was positive or negative by these standards, given only knowledge of the presence of certain language cues. Close scrutiny into this model can then allow assessment of the effectiveness of any particular cue in predicting the sentiment associated with a user's experience.

# Methodology

The raw data set was packaged within the Challenge Dataset distributed throughout the fifth round of the Yelp Dataset Challenge. Specifically, this data set included approximately 1.6 million reviews for 61 thousand businesses in ten cities across Europe and North America. In a preliminary cleaning, a longitude constraint was imposed upon businesses to eliminate all reviews made in French-speaking Montreal and other territories further east, as well as all reviews made for businesses that did not fall under the category of "Restaurants." At this stage, unsupported characters as well as most reviews written languages other than English were also removed.  
&nbsp;&nbsp;&nbsp;&nbsp;A total of 206 variables were created from English language cues hand-selected from a randomly-generated subset of the reviews. Of these, 203 are binary-categorical, each observation being assigned `TRUE` or `FALSE` according to whether the corresponding review contained the cue. One variable was generated from cues representing contrast (i.e., but, however, though), and observations were assigned values simply by the number of times the cue was detected. The last two variables quantify respectively the use of uppercase letters and the use of exclamation points. Specifically, the former contains ratios of the number of uppercase letters used over the total number of letters used, and the latter contains ratios of the number of exclamation points used over the combined number of exclamation points and periods used.  
&nbsp;&nbsp;&nbsp;&nbsp;In a secondary cleaning, the 203 categorical variables were evaluated for how much preference each had for one level of the response. This was quantified using the formula
\[
\theta_{cue} = \frac{\max{\left( p_{high,cue} , p_{low,cue} \right)}}{\min{\left( p_{high,cue} , p_{low,cue} \right)}},
\]
where
\[
p_{high,cue} = \mathrm{\frac{number \thinspace of \thinspace ``high" \thinspace reviews \thinspace with \thinspace cue}{total \thinspace numbers \thinspace of \thinspace ``high" \thinspace reviews}} \enskip \mathrm{and} \enskip p_{low,cue} = \mathrm{\frac{number \thinspace of \thinspace ``low" \thinspace reviews \thinspace with \thinspace cue}{total \thinspace number \thinspace of \thinspace ``low" \thinspace reviews}}.
\]
In words, $\theta_{cue}$ is the number of times more likely it is to encounter a cue when given one level than when given the other, so a variable that sorts well would theoretically have $\theta_{cue}$ far greater than 1. After elimination of all categorical variables with $\theta_{cue} < 2$, the final data set includes a sample of 921615 reviews and 102 predictor variables. 

# Results

***Present the results of your statistical analyses in detail, using text, figures, and tables, and including initial summaries and visualization of the data. THe presentation should focus on the prediction rules you obtained, using methods chosen from the course. Explain why you chose those methods over others.***

# Discussion

***Relate the results of your analyses back to your resarch question and topic area in a concluding discussion. Provide any suitable final remarks, such as discussing things you thought of trying but didn't (and why you didn't).***

